// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: complex.proto

package com.pool.proto;

public final class Complex {
  private Complex() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ComplexMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.pool.proto.ComplexMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .com.pool.proto.DummyMessage one_dummy = 2;</code>
     */
    boolean hasOneDummy();
    /**
     * <code>optional .com.pool.proto.DummyMessage one_dummy = 2;</code>
     */
    com.pool.proto.Complex.DummyMessage getOneDummy();
    /**
     * <code>optional .com.pool.proto.DummyMessage one_dummy = 2;</code>
     */
    com.pool.proto.Complex.DummyMessageOrBuilder getOneDummyOrBuilder();

    /**
     * <code>repeated .com.pool.proto.DummyMessage multi_dummy = 3;</code>
     */
    java.util.List<com.pool.proto.Complex.DummyMessage> 
        getMultiDummyList();
    /**
     * <code>repeated .com.pool.proto.DummyMessage multi_dummy = 3;</code>
     */
    com.pool.proto.Complex.DummyMessage getMultiDummy(int index);
    /**
     * <code>repeated .com.pool.proto.DummyMessage multi_dummy = 3;</code>
     */
    int getMultiDummyCount();
    /**
     * <code>repeated .com.pool.proto.DummyMessage multi_dummy = 3;</code>
     */
    java.util.List<? extends com.pool.proto.Complex.DummyMessageOrBuilder> 
        getMultiDummyOrBuilderList();
    /**
     * <code>repeated .com.pool.proto.DummyMessage multi_dummy = 3;</code>
     */
    com.pool.proto.Complex.DummyMessageOrBuilder getMultiDummyOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.pool.proto.ComplexMessage}
   */
  public  static final class ComplexMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.pool.proto.ComplexMessage)
      ComplexMessageOrBuilder {
    // Use ComplexMessage.newBuilder() to construct.
    private ComplexMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ComplexMessage() {
      multiDummy_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ComplexMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 18: {
              com.pool.proto.Complex.DummyMessage.Builder subBuilder = null;
              if (oneDummy_ != null) {
                subBuilder = oneDummy_.toBuilder();
              }
              oneDummy_ = input.readMessage(com.pool.proto.Complex.DummyMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(oneDummy_);
                oneDummy_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                multiDummy_ = new java.util.ArrayList<com.pool.proto.Complex.DummyMessage>();
                mutable_bitField0_ |= 0x00000002;
              }
              multiDummy_.add(
                  input.readMessage(com.pool.proto.Complex.DummyMessage.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          multiDummy_ = java.util.Collections.unmodifiableList(multiDummy_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pool.proto.Complex.internal_static_com_pool_proto_ComplexMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pool.proto.Complex.internal_static_com_pool_proto_ComplexMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pool.proto.Complex.ComplexMessage.class, com.pool.proto.Complex.ComplexMessage.Builder.class);
    }

    private int bitField0_;
    public static final int ONE_DUMMY_FIELD_NUMBER = 2;
    private com.pool.proto.Complex.DummyMessage oneDummy_;
    /**
     * <code>optional .com.pool.proto.DummyMessage one_dummy = 2;</code>
     */
    public boolean hasOneDummy() {
      return oneDummy_ != null;
    }
    /**
     * <code>optional .com.pool.proto.DummyMessage one_dummy = 2;</code>
     */
    public com.pool.proto.Complex.DummyMessage getOneDummy() {
      return oneDummy_ == null ? com.pool.proto.Complex.DummyMessage.getDefaultInstance() : oneDummy_;
    }
    /**
     * <code>optional .com.pool.proto.DummyMessage one_dummy = 2;</code>
     */
    public com.pool.proto.Complex.DummyMessageOrBuilder getOneDummyOrBuilder() {
      return getOneDummy();
    }

    public static final int MULTI_DUMMY_FIELD_NUMBER = 3;
    private java.util.List<com.pool.proto.Complex.DummyMessage> multiDummy_;
    /**
     * <code>repeated .com.pool.proto.DummyMessage multi_dummy = 3;</code>
     */
    public java.util.List<com.pool.proto.Complex.DummyMessage> getMultiDummyList() {
      return multiDummy_;
    }
    /**
     * <code>repeated .com.pool.proto.DummyMessage multi_dummy = 3;</code>
     */
    public java.util.List<? extends com.pool.proto.Complex.DummyMessageOrBuilder> 
        getMultiDummyOrBuilderList() {
      return multiDummy_;
    }
    /**
     * <code>repeated .com.pool.proto.DummyMessage multi_dummy = 3;</code>
     */
    public int getMultiDummyCount() {
      return multiDummy_.size();
    }
    /**
     * <code>repeated .com.pool.proto.DummyMessage multi_dummy = 3;</code>
     */
    public com.pool.proto.Complex.DummyMessage getMultiDummy(int index) {
      return multiDummy_.get(index);
    }
    /**
     * <code>repeated .com.pool.proto.DummyMessage multi_dummy = 3;</code>
     */
    public com.pool.proto.Complex.DummyMessageOrBuilder getMultiDummyOrBuilder(
        int index) {
      return multiDummy_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (oneDummy_ != null) {
        output.writeMessage(2, getOneDummy());
      }
      for (int i = 0; i < multiDummy_.size(); i++) {
        output.writeMessage(3, multiDummy_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (oneDummy_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getOneDummy());
      }
      for (int i = 0; i < multiDummy_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, multiDummy_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.pool.proto.Complex.ComplexMessage)) {
        return super.equals(obj);
      }
      com.pool.proto.Complex.ComplexMessage other = (com.pool.proto.Complex.ComplexMessage) obj;

      boolean result = true;
      result = result && (hasOneDummy() == other.hasOneDummy());
      if (hasOneDummy()) {
        result = result && getOneDummy()
            .equals(other.getOneDummy());
      }
      result = result && getMultiDummyList()
          .equals(other.getMultiDummyList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasOneDummy()) {
        hash = (37 * hash) + ONE_DUMMY_FIELD_NUMBER;
        hash = (53 * hash) + getOneDummy().hashCode();
      }
      if (getMultiDummyCount() > 0) {
        hash = (37 * hash) + MULTI_DUMMY_FIELD_NUMBER;
        hash = (53 * hash) + getMultiDummyList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.pool.proto.Complex.ComplexMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pool.proto.Complex.ComplexMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pool.proto.Complex.ComplexMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pool.proto.Complex.ComplexMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pool.proto.Complex.ComplexMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.pool.proto.Complex.ComplexMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.pool.proto.Complex.ComplexMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.pool.proto.Complex.ComplexMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.pool.proto.Complex.ComplexMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.pool.proto.Complex.ComplexMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.pool.proto.Complex.ComplexMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.pool.proto.ComplexMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.pool.proto.ComplexMessage)
        com.pool.proto.Complex.ComplexMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.pool.proto.Complex.internal_static_com_pool_proto_ComplexMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.pool.proto.Complex.internal_static_com_pool_proto_ComplexMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.pool.proto.Complex.ComplexMessage.class, com.pool.proto.Complex.ComplexMessage.Builder.class);
      }

      // Construct using com.pool.proto.Complex.ComplexMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMultiDummyFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (oneDummyBuilder_ == null) {
          oneDummy_ = null;
        } else {
          oneDummy_ = null;
          oneDummyBuilder_ = null;
        }
        if (multiDummyBuilder_ == null) {
          multiDummy_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          multiDummyBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.pool.proto.Complex.internal_static_com_pool_proto_ComplexMessage_descriptor;
      }

      public com.pool.proto.Complex.ComplexMessage getDefaultInstanceForType() {
        return com.pool.proto.Complex.ComplexMessage.getDefaultInstance();
      }

      public com.pool.proto.Complex.ComplexMessage build() {
        com.pool.proto.Complex.ComplexMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.pool.proto.Complex.ComplexMessage buildPartial() {
        com.pool.proto.Complex.ComplexMessage result = new com.pool.proto.Complex.ComplexMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (oneDummyBuilder_ == null) {
          result.oneDummy_ = oneDummy_;
        } else {
          result.oneDummy_ = oneDummyBuilder_.build();
        }
        if (multiDummyBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            multiDummy_ = java.util.Collections.unmodifiableList(multiDummy_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.multiDummy_ = multiDummy_;
        } else {
          result.multiDummy_ = multiDummyBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.pool.proto.Complex.ComplexMessage) {
          return mergeFrom((com.pool.proto.Complex.ComplexMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.pool.proto.Complex.ComplexMessage other) {
        if (other == com.pool.proto.Complex.ComplexMessage.getDefaultInstance()) return this;
        if (other.hasOneDummy()) {
          mergeOneDummy(other.getOneDummy());
        }
        if (multiDummyBuilder_ == null) {
          if (!other.multiDummy_.isEmpty()) {
            if (multiDummy_.isEmpty()) {
              multiDummy_ = other.multiDummy_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureMultiDummyIsMutable();
              multiDummy_.addAll(other.multiDummy_);
            }
            onChanged();
          }
        } else {
          if (!other.multiDummy_.isEmpty()) {
            if (multiDummyBuilder_.isEmpty()) {
              multiDummyBuilder_.dispose();
              multiDummyBuilder_ = null;
              multiDummy_ = other.multiDummy_;
              bitField0_ = (bitField0_ & ~0x00000002);
              multiDummyBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMultiDummyFieldBuilder() : null;
            } else {
              multiDummyBuilder_.addAllMessages(other.multiDummy_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.pool.proto.Complex.ComplexMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.pool.proto.Complex.ComplexMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.pool.proto.Complex.DummyMessage oneDummy_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.pool.proto.Complex.DummyMessage, com.pool.proto.Complex.DummyMessage.Builder, com.pool.proto.Complex.DummyMessageOrBuilder> oneDummyBuilder_;
      /**
       * <code>optional .com.pool.proto.DummyMessage one_dummy = 2;</code>
       */
      public boolean hasOneDummy() {
        return oneDummyBuilder_ != null || oneDummy_ != null;
      }
      /**
       * <code>optional .com.pool.proto.DummyMessage one_dummy = 2;</code>
       */
      public com.pool.proto.Complex.DummyMessage getOneDummy() {
        if (oneDummyBuilder_ == null) {
          return oneDummy_ == null ? com.pool.proto.Complex.DummyMessage.getDefaultInstance() : oneDummy_;
        } else {
          return oneDummyBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.pool.proto.DummyMessage one_dummy = 2;</code>
       */
      public Builder setOneDummy(com.pool.proto.Complex.DummyMessage value) {
        if (oneDummyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          oneDummy_ = value;
          onChanged();
        } else {
          oneDummyBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .com.pool.proto.DummyMessage one_dummy = 2;</code>
       */
      public Builder setOneDummy(
          com.pool.proto.Complex.DummyMessage.Builder builderForValue) {
        if (oneDummyBuilder_ == null) {
          oneDummy_ = builderForValue.build();
          onChanged();
        } else {
          oneDummyBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .com.pool.proto.DummyMessage one_dummy = 2;</code>
       */
      public Builder mergeOneDummy(com.pool.proto.Complex.DummyMessage value) {
        if (oneDummyBuilder_ == null) {
          if (oneDummy_ != null) {
            oneDummy_ =
              com.pool.proto.Complex.DummyMessage.newBuilder(oneDummy_).mergeFrom(value).buildPartial();
          } else {
            oneDummy_ = value;
          }
          onChanged();
        } else {
          oneDummyBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .com.pool.proto.DummyMessage one_dummy = 2;</code>
       */
      public Builder clearOneDummy() {
        if (oneDummyBuilder_ == null) {
          oneDummy_ = null;
          onChanged();
        } else {
          oneDummy_ = null;
          oneDummyBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .com.pool.proto.DummyMessage one_dummy = 2;</code>
       */
      public com.pool.proto.Complex.DummyMessage.Builder getOneDummyBuilder() {
        
        onChanged();
        return getOneDummyFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.pool.proto.DummyMessage one_dummy = 2;</code>
       */
      public com.pool.proto.Complex.DummyMessageOrBuilder getOneDummyOrBuilder() {
        if (oneDummyBuilder_ != null) {
          return oneDummyBuilder_.getMessageOrBuilder();
        } else {
          return oneDummy_ == null ?
              com.pool.proto.Complex.DummyMessage.getDefaultInstance() : oneDummy_;
        }
      }
      /**
       * <code>optional .com.pool.proto.DummyMessage one_dummy = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.pool.proto.Complex.DummyMessage, com.pool.proto.Complex.DummyMessage.Builder, com.pool.proto.Complex.DummyMessageOrBuilder> 
          getOneDummyFieldBuilder() {
        if (oneDummyBuilder_ == null) {
          oneDummyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.pool.proto.Complex.DummyMessage, com.pool.proto.Complex.DummyMessage.Builder, com.pool.proto.Complex.DummyMessageOrBuilder>(
                  getOneDummy(),
                  getParentForChildren(),
                  isClean());
          oneDummy_ = null;
        }
        return oneDummyBuilder_;
      }

      private java.util.List<com.pool.proto.Complex.DummyMessage> multiDummy_ =
        java.util.Collections.emptyList();
      private void ensureMultiDummyIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          multiDummy_ = new java.util.ArrayList<com.pool.proto.Complex.DummyMessage>(multiDummy_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.pool.proto.Complex.DummyMessage, com.pool.proto.Complex.DummyMessage.Builder, com.pool.proto.Complex.DummyMessageOrBuilder> multiDummyBuilder_;

      /**
       * <code>repeated .com.pool.proto.DummyMessage multi_dummy = 3;</code>
       */
      public java.util.List<com.pool.proto.Complex.DummyMessage> getMultiDummyList() {
        if (multiDummyBuilder_ == null) {
          return java.util.Collections.unmodifiableList(multiDummy_);
        } else {
          return multiDummyBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.pool.proto.DummyMessage multi_dummy = 3;</code>
       */
      public int getMultiDummyCount() {
        if (multiDummyBuilder_ == null) {
          return multiDummy_.size();
        } else {
          return multiDummyBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.pool.proto.DummyMessage multi_dummy = 3;</code>
       */
      public com.pool.proto.Complex.DummyMessage getMultiDummy(int index) {
        if (multiDummyBuilder_ == null) {
          return multiDummy_.get(index);
        } else {
          return multiDummyBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.pool.proto.DummyMessage multi_dummy = 3;</code>
       */
      public Builder setMultiDummy(
          int index, com.pool.proto.Complex.DummyMessage value) {
        if (multiDummyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMultiDummyIsMutable();
          multiDummy_.set(index, value);
          onChanged();
        } else {
          multiDummyBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.pool.proto.DummyMessage multi_dummy = 3;</code>
       */
      public Builder setMultiDummy(
          int index, com.pool.proto.Complex.DummyMessage.Builder builderForValue) {
        if (multiDummyBuilder_ == null) {
          ensureMultiDummyIsMutable();
          multiDummy_.set(index, builderForValue.build());
          onChanged();
        } else {
          multiDummyBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.pool.proto.DummyMessage multi_dummy = 3;</code>
       */
      public Builder addMultiDummy(com.pool.proto.Complex.DummyMessage value) {
        if (multiDummyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMultiDummyIsMutable();
          multiDummy_.add(value);
          onChanged();
        } else {
          multiDummyBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.pool.proto.DummyMessage multi_dummy = 3;</code>
       */
      public Builder addMultiDummy(
          int index, com.pool.proto.Complex.DummyMessage value) {
        if (multiDummyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMultiDummyIsMutable();
          multiDummy_.add(index, value);
          onChanged();
        } else {
          multiDummyBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.pool.proto.DummyMessage multi_dummy = 3;</code>
       */
      public Builder addMultiDummy(
          com.pool.proto.Complex.DummyMessage.Builder builderForValue) {
        if (multiDummyBuilder_ == null) {
          ensureMultiDummyIsMutable();
          multiDummy_.add(builderForValue.build());
          onChanged();
        } else {
          multiDummyBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.pool.proto.DummyMessage multi_dummy = 3;</code>
       */
      public Builder addMultiDummy(
          int index, com.pool.proto.Complex.DummyMessage.Builder builderForValue) {
        if (multiDummyBuilder_ == null) {
          ensureMultiDummyIsMutable();
          multiDummy_.add(index, builderForValue.build());
          onChanged();
        } else {
          multiDummyBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.pool.proto.DummyMessage multi_dummy = 3;</code>
       */
      public Builder addAllMultiDummy(
          java.lang.Iterable<? extends com.pool.proto.Complex.DummyMessage> values) {
        if (multiDummyBuilder_ == null) {
          ensureMultiDummyIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, multiDummy_);
          onChanged();
        } else {
          multiDummyBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.pool.proto.DummyMessage multi_dummy = 3;</code>
       */
      public Builder clearMultiDummy() {
        if (multiDummyBuilder_ == null) {
          multiDummy_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          multiDummyBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.pool.proto.DummyMessage multi_dummy = 3;</code>
       */
      public Builder removeMultiDummy(int index) {
        if (multiDummyBuilder_ == null) {
          ensureMultiDummyIsMutable();
          multiDummy_.remove(index);
          onChanged();
        } else {
          multiDummyBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.pool.proto.DummyMessage multi_dummy = 3;</code>
       */
      public com.pool.proto.Complex.DummyMessage.Builder getMultiDummyBuilder(
          int index) {
        return getMultiDummyFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.pool.proto.DummyMessage multi_dummy = 3;</code>
       */
      public com.pool.proto.Complex.DummyMessageOrBuilder getMultiDummyOrBuilder(
          int index) {
        if (multiDummyBuilder_ == null) {
          return multiDummy_.get(index);  } else {
          return multiDummyBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.pool.proto.DummyMessage multi_dummy = 3;</code>
       */
      public java.util.List<? extends com.pool.proto.Complex.DummyMessageOrBuilder> 
           getMultiDummyOrBuilderList() {
        if (multiDummyBuilder_ != null) {
          return multiDummyBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(multiDummy_);
        }
      }
      /**
       * <code>repeated .com.pool.proto.DummyMessage multi_dummy = 3;</code>
       */
      public com.pool.proto.Complex.DummyMessage.Builder addMultiDummyBuilder() {
        return getMultiDummyFieldBuilder().addBuilder(
            com.pool.proto.Complex.DummyMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .com.pool.proto.DummyMessage multi_dummy = 3;</code>
       */
      public com.pool.proto.Complex.DummyMessage.Builder addMultiDummyBuilder(
          int index) {
        return getMultiDummyFieldBuilder().addBuilder(
            index, com.pool.proto.Complex.DummyMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .com.pool.proto.DummyMessage multi_dummy = 3;</code>
       */
      public java.util.List<com.pool.proto.Complex.DummyMessage.Builder> 
           getMultiDummyBuilderList() {
        return getMultiDummyFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.pool.proto.Complex.DummyMessage, com.pool.proto.Complex.DummyMessage.Builder, com.pool.proto.Complex.DummyMessageOrBuilder> 
          getMultiDummyFieldBuilder() {
        if (multiDummyBuilder_ == null) {
          multiDummyBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.pool.proto.Complex.DummyMessage, com.pool.proto.Complex.DummyMessage.Builder, com.pool.proto.Complex.DummyMessageOrBuilder>(
                  multiDummy_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          multiDummy_ = null;
        }
        return multiDummyBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.pool.proto.ComplexMessage)
    }

    // @@protoc_insertion_point(class_scope:com.pool.proto.ComplexMessage)
    private static final com.pool.proto.Complex.ComplexMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.pool.proto.Complex.ComplexMessage();
    }

    public static com.pool.proto.Complex.ComplexMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ComplexMessage>
        PARSER = new com.google.protobuf.AbstractParser<ComplexMessage>() {
      public ComplexMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ComplexMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ComplexMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ComplexMessage> getParserForType() {
      return PARSER;
    }

    public com.pool.proto.Complex.ComplexMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DummyMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.pool.proto.DummyMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>optional string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code com.pool.proto.DummyMessage}
   */
  public  static final class DummyMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.pool.proto.DummyMessage)
      DummyMessageOrBuilder {
    // Use DummyMessage.newBuilder() to construct.
    private DummyMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DummyMessage() {
      id_ = 0;
      name_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private DummyMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pool.proto.Complex.internal_static_com_pool_proto_DummyMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pool.proto.Complex.internal_static_com_pool_proto_DummyMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pool.proto.Complex.DummyMessage.class, com.pool.proto.Complex.DummyMessage.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>optional int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.pool.proto.Complex.DummyMessage)) {
        return super.equals(obj);
      }
      com.pool.proto.Complex.DummyMessage other = (com.pool.proto.Complex.DummyMessage) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getName()
          .equals(other.getName());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.pool.proto.Complex.DummyMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pool.proto.Complex.DummyMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pool.proto.Complex.DummyMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pool.proto.Complex.DummyMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pool.proto.Complex.DummyMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.pool.proto.Complex.DummyMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.pool.proto.Complex.DummyMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.pool.proto.Complex.DummyMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.pool.proto.Complex.DummyMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.pool.proto.Complex.DummyMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.pool.proto.Complex.DummyMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.pool.proto.DummyMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.pool.proto.DummyMessage)
        com.pool.proto.Complex.DummyMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.pool.proto.Complex.internal_static_com_pool_proto_DummyMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.pool.proto.Complex.internal_static_com_pool_proto_DummyMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.pool.proto.Complex.DummyMessage.class, com.pool.proto.Complex.DummyMessage.Builder.class);
      }

      // Construct using com.pool.proto.Complex.DummyMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.pool.proto.Complex.internal_static_com_pool_proto_DummyMessage_descriptor;
      }

      public com.pool.proto.Complex.DummyMessage getDefaultInstanceForType() {
        return com.pool.proto.Complex.DummyMessage.getDefaultInstance();
      }

      public com.pool.proto.Complex.DummyMessage build() {
        com.pool.proto.Complex.DummyMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.pool.proto.Complex.DummyMessage buildPartial() {
        com.pool.proto.Complex.DummyMessage result = new com.pool.proto.Complex.DummyMessage(this);
        result.id_ = id_;
        result.name_ = name_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.pool.proto.Complex.DummyMessage) {
          return mergeFrom((com.pool.proto.Complex.DummyMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.pool.proto.Complex.DummyMessage other) {
        if (other == com.pool.proto.Complex.DummyMessage.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.pool.proto.Complex.DummyMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.pool.proto.Complex.DummyMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>optional int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.pool.proto.DummyMessage)
    }

    // @@protoc_insertion_point(class_scope:com.pool.proto.DummyMessage)
    private static final com.pool.proto.Complex.DummyMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.pool.proto.Complex.DummyMessage();
    }

    public static com.pool.proto.Complex.DummyMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DummyMessage>
        PARSER = new com.google.protobuf.AbstractParser<DummyMessage>() {
      public DummyMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new DummyMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DummyMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DummyMessage> getParserForType() {
      return PARSER;
    }

    public com.pool.proto.Complex.DummyMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_pool_proto_ComplexMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_pool_proto_ComplexMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_pool_proto_DummyMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_pool_proto_DummyMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rcomplex.proto\022\016com.pool.proto\"t\n\016Compl" +
      "exMessage\022/\n\tone_dummy\030\002 \001(\0132\034.com.pool." +
      "proto.DummyMessage\0221\n\013multi_dummy\030\003 \003(\0132" +
      "\034.com.pool.proto.DummyMessage\"(\n\014DummyMe" +
      "ssage\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_pool_proto_ComplexMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_pool_proto_ComplexMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_pool_proto_ComplexMessage_descriptor,
        new java.lang.String[] { "OneDummy", "MultiDummy", });
    internal_static_com_pool_proto_DummyMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_pool_proto_DummyMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_pool_proto_DummyMessage_descriptor,
        new java.lang.String[] { "Id", "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
